version: '3'
services:
  library_be:
    image: library:latest
    depends_on:
      - library_db
    ports:
      - "8080:8080"
  library_db:
    image: postgres:14.3
    volumes:
      - library_postgres_data:/var/lib/postgresql/data
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_DB=postgresDB
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432" ]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s
    # dynamoDB:
    #   image: "amazon/dynamodb-local:latest"
    #   container_name: "dynamodb_birey_local"
    #   working_dir: /home/dynamodblocal
    #   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    #   ports:
    #     - "8000:8000"
    #   volumes:
    #     - "dynamodb_local_data:/home/dynamodblocal/data"

volumes:
  library_postgres_data:
    external: true
